### PR TITLE
Adding United States state boundaries from OSM data

### PR DESCRIPTION
**Pull request by b-jazz**
I wrote a script to download relations from OSM and combine the relations' ways into a single Polygon (or multiple polygons for states like Michigan or islands off of California) and output a geojson file. I checked the first dozen of these and they all seem just fine.

### CODE REVIEW

**Comment by georgique** [comment]
Looks cool, thanks for this.

**Comment by georgique** [comment]
Hey, you able to share your script? I would use it for other countries too.

**Comment by b-jazz** [comment]
Absolutely. It’s pretty crappy in terms of code quality, but it gets the
job done. It’s a single file but pulls in a couple of modules (geojson and
OsmApi). Are you familiar enough with python and pip to figure out how to
install the modules or do you need me to properly package it up?

Either way, I won’t be able to get to it until I’m back at my computer.

**Comment by georgique** [comment]
I have some experience with Python, but not much. If it's not a big deal for you to ease up using the script, I'd appreciate that.

**Comment by b-jazz** [comment]
Okay, give this a try:

https://gitlab.com/b-jazz/osmrel2geojson

**Comment by georgique** [comment]
@b-jazz Thanks! I'll try it out soon.

**Comment by georgique** [comment]
Hey @b-jazz, I've just got time to work on your script. All went well during installation, but when I tried to download actual data, I got the following error:
`
Traceback (most recent call last):
  File "/home/george/.local/bin/osmrel2geojson", line 7, in <module>
    from osmrel2geojson.or2gj import main
  File "/home/george/.local/lib/python3.6/site-packages/osmrel2geojson/or2gj.py", line 4, in <module>
    from geojson import dumps, Polygon, Feature, FeatureCollection
ModuleNotFoundError: No module named 'geojson'
`
Feeling this is something easy to fix, can you please help?

**Comment by b-jazz** [comment]
If have you have pip3 installed, you should be able to just run `pip3 install geojson`.

**Comment by georgique** [comment]
Supercool, it worked! I'm gonna add other big countries' states to the repo soon.

**Pull request merged**
